sudo: required
services:
  - docker

before_install:
  - docker build -t complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true complex npm test

after_success:
  - docker build -t jiaqiwang118/multi-client ./client
  - docker build -t jiaqiwang118/multi-nginx ./nginx
  - docker build -t jiaqiwang118/multi-server ./server
  - docker build -t jiaqiwang118/multi-worker ./worker
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push jiaqiwang118/multi-client
  - docker push jiaqiwang118/multi-nginx
  - docker push jiaqiwang118/multi-server
  - docker push jiaqiwang118/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-197642979598'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY